### PR TITLE
Main Gui

### PR DESCRIPTION
**Pull request by owenlim225**
pre wag mo reject pagod, dugo, puyat, pawis koto BAWHWAHWAHWAHAH

### CODE REVIEW

**Comment by ChristianJude23** [comment]
BWHAHAHAHAHA

**Comment by owenlim225** [comment]
> Owner

merge na!!!!!!!!!!!!!!!!!! >:(

**Comment by ChristianJude23** [comment]
Mawawala 689 lines of code natin BWAHAHAHAAHAH

**Comment by ChristianJude23** [comment]
Dyan lang yan pangkuha ng needs

**Comment by ChristianJude23** [comment]
BWAHAHAHAHAHA

**Pull request closed without merging**
